### ISSUE TITLE
Email setup

### ISSUE THREAD

**Issue by cyberfarer** [pydio/cells#1]
`2018-05-17T13:55:17.854-0400	ERROR	pydio.grpc.tasks	{"id":"","code":0,"detail":"consuming queue had 5 errors (successfully sent 0), errors were error while trying to send email: NewGomailMessage: cannot find FROM address. Will retry next time,\nerror while trying to send email: NewGomailMessage: cannot find FROM address. Will retry next time,\nerror while trying to send email: NewGomailMessage: cannot find FROM address. Will retry next time,\nerror while trying to send email: NewGomailMessage: cannot find FROM address. Will retry next time,\nerror while trying to send email: dial tcp: lookup my.smtp.server on no such host. Will retry next time","status":""}`

All of this info is set and displays in both the frontend and through the cli. 

Thanks.

**Comment by cyberfarer** [comment]
I got it to work on a restart. So, for the messages in the queue that will not send, how do I clear them? Thanks.

**Comment by cdujeu** [comment]
Hey @cyberfarer, big up for the #1 issue :-)
As you have noticed : 
- As of now, you have to restart after changing Mailer configuration.
- The queue will try 5 times to send and discard otherwise. So it should be cleared automatically at one point. 
Please confirm and close if it's ok for you.
Charles
