### ISSUE TITLE
Feature suggestion: allow passing more parameters to Caddy (without recompiling)

### ISSUE THREAD

**Issue by GwynethLlewelyn** [pydio/cells#129]
Cells uses [Caddy](https://github.com/mholt/caddy) as a front-end web server; Caddy is a wonderful solution for many reasons, one of which is that it can be 'embedded' inside an application (as Cells does!) and therefore does not require a separate installation (and configuration!).
However, Cells is very sparse in the amount of Caddy configuration parameters that can be passed using the `pydio.json` configuration file; at the time of writing, if I'm not mistaken, the only ones that get passed are the paths to server certificates (or a flag saying that these are self-signed) and an option to turn SSL on or off. Caddy, however, is a very sophisticated piece of software; it would be nice to be able to have a section somewhere inside the `pydio.json` file with a list of parameters to be passed directly to Caddy.
For example, I have noticed that HTTP/2 is explicitly disabled (allegedly, according to the developers, because there was an issue with WebSockets). It's easy enough to fix that (if you wish full HTTP/2 support, which is Caddy's default), just change a line of code, and recompile... however, on a production environment, I believe it would be much better to have all these options on a configuration file.
An alternative would be to directly load a Caddyfile (instead of having Cells generating one in memory), starting with some reasonable defaults provided by Pydio. That would probably be easier to implement and possibly more 'future-proof' — as Caddy evolves and adds more features and functionality, Cells will not need to worry to keep up with Caddy's changes, it would just update the default Caddyfile...
(Disclaimer: I'm not a Caddy user myself, so what I'm suggesting might actually be impossible or undesirable!)

**Comment by hellhond** [comment]
First, great work with both legacy Pydio and the new Pydio Cells, they're both amazing!

Another example to OP's request is to add the Access-Control-Allow-Origin header to the Caddy config, so that when using access proxies (e.g. Pritunl Zero), browsers won't reject the request.

Another is adding alias hosts to the Caddy config file that can resolve the 'is not served on this interface' Caddy error. Use case for this is when regular requests are handled by a proxy, like Nginx, but WebDAV requests are handled by Caddy/Cells directly.
We had an issue when uploading files via DAV, which passed via Nginx, Cells would generate webdav:locked errors (#252).

Maybe storing a Caddy config template, or the full config file of Caddy in the same .config path as pydio.json, would allow some great flexibility to whoever wants to add some Caddy parameters.
