### ISSUE TITLE
Intentions with PHP plugins under cells-front

### ISSUE THREAD

**Issue by bures** [pydio/cells#13]
Please, what is the intended future of the PHP plugins under cells-front (in particular search and metadata)? It seems to me that the idea is that computation and storage is to be handled by Go microservices. The UI is to be handled by PHP.

Do I understand right in this context that for instance the index.pydio plugin has been rewritten to handle only formulation of search queries, which it send to Go microservice that internally utilizes Bleve?

I'm asking because I see some divergence between comments/manifests and the actual implementation. So I'm checking if my understanding is correct.

Thanks.

**Comment by cdujeu** [comment]
Hi Tomas, 
U got it entirely. And actually in the very next version, the "cells-front" project will be dropped ! But no panic, most of the plugins ( = now only XML and JS, no more PHP) will be found in the cells repository. 
You should have a look at the latest developments on branch gokilledphpstars. This is the near (and bright!) future without php anymore. Look at frontend/front-srv/assets, you'll find the old plugins there, and see how they are rewritten to use the actual micro-services APIs instead of some php-legacy api's themselves talking to micro-services.
hope it's clear ;-)
Charles

**Comment by bures** [comment]
Hello Charles,

thanks a lot for explanation and pointing me to the new style of plugins. I'll have a look and already go this path, once I port the plugin. 

Tomas
