### ISSUE TITLE
build static binary

### ISSUE THREAD

**Issue by aptalca** [pydio/cells#184]
Hi, I've been trying to build a static binary and miserably failing. Can you point me to your code for building the static binary you distribute via the website?

I can build the binary just fine (via ` go build main.go`) and it works, but it only works as long as the src/github.com/pydio/cells location is present. I can't run the binary by itself.

I'm using an alpine baseimage with gcc and go 1.12.12

I tried to build with `CGO_ENABLED=0` but that fails due to the sqlite3 dependency (cgo app).
I also tried `-ldflags '-w -extldflags "-static"'` but that also is unsuccessful.

Ultimately, I'll try to build it for arm32v7 and arm64v8 but first things first.

Thanks

**Comment by bsinou** [comment]
Hello @aptalca 

As stated many times in the doc (that you seem to not have read very well :) ), please rather use the forum for such question.

Thus said, you should have a look at the Makefile.

And  the bonus: your binary does not work when you move it because you miss the static files.
Before deployment, you should perform a `make clean generate` before building the binary.
