### ISSUE TITLE
Enable the modification of templates paths

### ISSUE THREAD

**Issue by Arno500** [pydio/cells#186]
It seems the functionality is not enabled yet, since we can't modify the text on the page (https://host/settings/data/template-paths), only navigate in it and Ctrl+Space to checks suggestions.
It virtually renders the S3 function unusable, since everything gets into the same directory, whether they are personal files or common ones (excepted if you follow the rule: 1 bucket 1 cell).

**Comment by cdujeu** [comment]
hello @Arno500 
Template path customization is in fact a feature of cells-enterprise. Maybe it's probably not very clear in the interface.
However I don't really get why "it renders the S3 function unusable", could you be more specific about what you want to achieve?
Side-note, PLEASE next time post in the forum instead of GH, we try to keep issues for "qualified bugs" only ;-) 
Thx

**Comment by Arno500** [comment]
(sorry for the issue, noting for next time!)
Currently the only thing I can do is to set the personal-files location to S3 (thus the root in the space equals to the root of the configured bucket). It prevents me from using the same bucket for other users or even workspaces.
Actually, what I want is storing all the files from all the users and workspaces into one single bucket. Without the template path modification, every file I copy to a workspace located on the bucket gets replicated to every workspace, since they share the same storage.
Also, it does prevent from using S3 for user storage (since the root of the bucket needs to be the root of the user). Or following what I said, 1 bucket for 1 user or workspace.
A possible solution would be to dissociate storage and template paths. In my case it would perfectly fits my needs.
