### ISSUE TITLE
Describe the YAML expected by `cells install --yaml ...`

### ISSUE THREAD

**Issue by drzraf** [pydio/cells#199]
It sounds like an interesting option but it lacks the expected YAML schema.

**Comment by bsinou** [comment]
In fact it is still a work in progress, the API must still evolve in next minor and major version to adapt to new installation process: 
- in 2.1 (with the removal of the `dex` library) 
- in 3.x (addition of the multi URL option)

That is the reason why it is not yet documented and officially supported.

Yet, it already works. You can find an example here: https://github.com/pydio/cells/tree/master/tools/docker/compose/quickstart for the installer and various configuration sample for the main proxy here: https://github.com/pydio/cells/tree/master/cmd/testdata

Both yaml and json are supported.

The idea is to mimic the browser installation by providing a file that contains all the information that is normally posted by end-admin's browser at the end of the installation wizard.

The trick is also to pass the exit_after_install flag so that the server restarts cleanly once the automated install has been done.

I would be happy to hear your feedback and comment on this. @drzraf  @v-byte-cpu : if you want, I can also invite you to our developer chat-room to discuss this more informally, just let me know.

**Comment by cn6103** [comment]
Looking at this issue as I am also looking for a silent/automated install method for large deployment.

While some of the basics are covered in the examples pointed to, there are some things seem to not be exposed via the yaml file or command flags (like inserting license key, adding datasources[such as s3 sources], log configuring, adding enterprise features like ldap, etc).

Updated links looking at for current examples:
https://github.com/pydio/cells/tree/master/cmd/sampleconf
https://github.com/pydio/cells/tree/master/tools/docker/compose


Is there better documentation being generated? Or is this still a feature not supported by vendor development?

**Comment by cdujeu** [comment]
added in the v4 doc
