### ISSUE TITLE
cannot use rest api with oauth2 client (grant_types client_credentials)

### ISSUE THREAD

**Issue by yguenneugues** [pydio/cells#258]
Hi,
My access token is invalid when it provided from an oauth2 client (grant_types client_credentials)

Pydio Cells version:

```
Pydio Cells Enterprise Distribution
 Version:       2.1.4
 Built:         07 Aug 20 06:57 +0000
 Git commit:    7926c4b3ad50dee9de84f3791100454c851ce991
 OS/Arch:       linux/amd64
 Go version:    go1.13.12
```
Custom oauth2 client config: (grant_types client_credentials)
```
{
  "client_id": "my_client",
  "client_name": "my_client",
  "client_secret": "password",
  "grant_types": [
    "client_credentials"
  ],
  "redirect_uris": null,
  "response_types": [
    "code",
    "token",
    "id_token"
  ],
  "scope": "openid email profile pydio offline"
}
```

**Step 1: Get an valid access token**
Request:
```
POST /oidc/oauth2/token 
Host: https://host-pydio.com
Header : 
Authorization Basic bXlfY2xpZW50OnBhc3N3b3Jk ( client_id=my_client & client_secret=password)
Body:
grant_type=client_credentials
```

Response:
```
HTTP/1.1 200 OK
Content-Type: application/json
{
    "access_token": "RIIFAxI5g4kYsXSeaqz0uhDnDp-dJyuE8w3qxuB2HlQ.82-l-FUpAQljJBHMNJNWR88sIFIyT7MijQRq-q9kt3o",
    "expires_in": 599,
    "scope": "",
    "token_type": "bearer"
}
```

**Step 2: call api with access token ( doesn't works)**
Request:
```
GET /a/user/xxx@test.com 
Host: https://host-pydio.com
Header : 
Authorization Bearer RIIFAxI5g4kYsXSeaqz0uhDnDp-dJyuE8w3qxuB2HlQ.82-l-FUpAQljJBHMNJNWR88sIFIyT7MijQRq-q9kt3o
```
Response:
```
HTTP/1.1 401 Unauthorized
Content-Type: application/json
```

```
pydio.log
{"level":"error","ts":"2020-08-31T10:45:21+02:00","logger":"pydio.rest.user","msg":"got a token but failed to load claims","SpanUuid":"4dba2198-eb66-11ea-9a41-005056908fbb","RemoteAddress":"X.X.X.X","UserAgent":"PostmanRuntime/7.26.3","HttpProtocol":"HTTP/1.1","error":"please provide at least one of login, uuid or queries"}

audit.log:
{"level":"error","ts":"2020-08-31T10:45:21+02:00","logger":"pydio.rest.user","msg":"Blocked invalid JWT","LogType":"audit","SpanUuid":"4dba2198-eb66-11ea-9a41-005056908fbb","RemoteAddress":"X.X.X.X","UserAgent":"PostmanRuntime/7.26.3","HttpProtocol":"HTTP/1.1","MsgId":"4"}
```

I searched in source code why i get this error. Its seems to be the jwt token is not correct.

in jwt.go
```
claims := &claim.Claims{}
if err := j.loadClaims(ctx, idToken, claims); err != nil {
	log.Logger(ctx).Error("got a token but failed to load claims", zap.Error(err))
	return ctx, *claims, err
}
```

In database, hydra_oauth2_access:
column session_data
`{"idToken":{"Claims":{"JTI":"","Issuer":"https://host-pydio.com/oidc/","Subject":"","Audience":null,"Nonce":"","ExpiresAt":"0001-01-01T00:00:00Z","IssuedAt":"2020-08-31T08:45:12.495933725Z","RequestedAt":"0001-01-01T00:00:00Z","AuthTime":"0001-01-01T00:00:00Z","AccessTokenHash":"","AuthenticationContextClassReference":"","CodeHash":"","Extra":null},"Headers":{"Extra":null},"ExpiresAt":{"access_token":"2020-08-31T08:55:12.495876569Z"},"Username":"","Subject":"client_id"},"extra":{},"KID":"","ClientID":"my_client","ConsentChallenge":""}
`

Maybe you will have to define a default user for the oauth2 client  and set it in jwt token ?

Thanks for your help

**Comment by ghecquet** [comment]
Hi there, thanks for your report.

According to the OAuth documentation, the Client Credentials grant is used when applications request an access token to access their own resources, not on behalf of a user. 
So for example it could be used if you were building your own API, and didn't want to create your own authentication server, and instead were trusing your Pydio Cells instance to issue and verify tokens, without the context of a Pydio Cells user. That means that the issued tokens are not usable for any of the Pydio Cells resource... and that is exactly what's happenning here (you are trying to access the Pydio Cells API).

In order to access the Pydio Cells API, you will need to use the authorization_code flow with a new or existing client, and have a user signing in so that it can set the appropriate context. There is no way to access the API without a user context because Pydio Cells is based on permissions.

I hope that this answers your question and satisfies your needs.

Thanks,
Greg

**Comment by yguenneugues** [comment]
Thank you for you answer.
I want to access pydio ressources through the API for an private external app. But when i use the authorization_code flow, the authorization code needs to be retrieved via a browser.
There is a method to get an acces token without needing a manual step ? (open browser )

**Comment by ghecquet** [comment]
OAuth was actually designed to avoid having a third party app have any access to a user's password. There is a grant type called the Resource Owner Password Credentials Grant but it currently is not implemented as it is not recommended for use.

You may be able to achieve what you want by simply having a refresh mechanism that keeps your access token alive without any manual intervention (apart from the initial retrieval of the access / refresh token). It's what most apps do. Would that be suitable for you ?

I'm closing this issue now because Github is only for qualified bugs. But feel free to post something in the Pydio forum if you want to keep that discussion alive.

Thanks,
Greg
