### ISSUE TITLE
could not get authentication token

### ISSUE THREAD

**Issue by AhatLi** [pydio/cells#261]
I issued a certificate from sslforfree for use in pydio.
The installation is complete and everything seems to be fine.

However, when I enter the URL in the Android application and click connect, display this message.
"Unable to verify server certificate"

enter ID PASS in the login window and Click connect and display message.
"could not get authentication token"

Even if you select your own certificate during cells install, you cannot connect from Android.

Can't use sslforfree's certificate in pydio android app?
Can't I use https in the pydio andorid app?

**Comment by bsinou** [comment]
Hello, 

> Can't use sslforfree's certificate in pydio android app?
We did not try this provider yet, but theoretically, if they provide valid certificates, it should work.

>  Can't I use https in the pydio andorid app?
Yes, but for the time being, only using standard 443 SSL port.

Can you normally connect to your server with a web browser (from your computer)? 

Could you provide more logs (from both server and the app) so that we can have a look ? 

PS: Furthermore, we would be grateful for such questions to be asked first on the forum, and only open an issue in one of the github repo once we could reproduce the bug on our side... Thanks for understanding.
