### ISSUE TITLE
[CLI installer] no way to back out if password is mi-typed first time

### ISSUE THREAD

**Issue by Zedsquared** [pydio/cells#275]
When installing (CLI) I found I had obviously mis-typed the admin password that I wanted to set, as the second entry of the password was flagged as a mismatch. There appears to be no way to go back and try entering the password again from the start, only further opportunities to try and confirm an unknown password.

I had to abort the installation and start again.

**Comment by bsinou** [comment]
Hello, 

Thanks for the report. 
Can you _"go"_ ? 
If such, it is in a quite understandable part of the code: you can have a look and suggest a pull request.
Otherwise, we will put that in the backlog, but with low priority, we have a lot to do with the soon coming 2.2 version and starting again from the beginning if you mistype your password is annoying but not blocker at all....

If you want to give a try, you can have a look at https://github.com/pydio/cells/blob/master/cmd/install-cli.go, line 165, the behaviour you expect is already implemented for the DB a few line above.
