### ISSUE TITLE
Why it use only EncFS?

### ISSUE THREAD

**Issue by dumprop** [pydio/cells#299]
I really like pydio project at first glance, but I'm really interested in security model

On https://pydio.com/en/docs/kb/pydio-8/pydio-security-model said that it uses EncFS

But seems that CryFS/gocryptfs may be better for security/speed
https://defuse.ca/audits/encfs.htm
https://www.cryfs.org/comparison
https://nuetzlich.net/gocryptfs/comparison/

Also seafile support Encrypted Libraries
https://help.seafile.com/security_and_encryption/use_encrypted_libraries/

So, on client side encrypted only some folders, not all files
Maybe that will be in pydio too?

**Comment by cdujeu** [comment]
Hi @dumprop 
Sorry but this is off-topic: you are pointing to the **Pydio 8** documentation, which is our legacy product in PHP that was indeed using EncFS. 
But Pydio Cells is providing its own encryption at rest implementation and does **not** rely on EncFS ! 
Closing, please use the forum instead of github issue for that kind of question next time, thanks!
