### ISSUE TITLE
Support Sqlite?

### ISSUE THREAD

**Issue by DUOLabs333** [pydio/cells#376]
Because of constraints, I can only use embedded filesystem DBs, like SQLite. Is it already supported or planned to be supported?

**Comment by cdujeu** [comment]
Hi, not out-of-the-box. 
That said, most services are unit-tested using sqlite implementation of the DAOs. So you could maybe try to recompile with the proper imports (go sqlite driver), and change the database configuration to point to sqlite files (using go sql dsn syntax). I say "files" because I think that each db-based service would probably need to have its own sqlite to avoid locks. 
Not that simple i admit :-)
